# Generated by Django 6.0.3 on 2026-06-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='risk_score',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='savings_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='savings_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='timeline_status',
            field=models.CharField(default='Confirmed', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_person',
            field=models.CharField(default='John Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_ai_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='risk_score',
            field=models.IntegerField(default=15),
        ),
    ]
